### ISSUE TITLE
请问怎么运行呢？我下载了go

### ISSUE THREAD

**Issue by zzlKevin** [byebyebruce/bailian2openai#3]
PS D:\GOproject\bailian2openai-master> go build -o bailian2openai cmd/bailian2openai/main.go
# command-line-arguments
cmd\bailian2openai\main.go:40:3: undefined: CLI
cmd\bailian2openai\main.go:43:12: undefined: RunAPIServer
PS D:\GOproject\bailian2openai-master>

报错了
我对go 和 docker都是第一次接触，不过go环境安装了，请问怎么运行呢，非常感谢

**Comment by byebyebruce** [comment]
go build -o bailian2openai cmd/bailian2openai

https://www.freeaihunter.com/?continueFlag=b3d383cbb55fe358c9377876edf08c4b
各种免费白嫖大模型了，不需要这么绕的方式了

**Comment by zzlKevin** [comment]
可以了，还得是gpt4看得明白，原来是运行  go run ./cmd/bailian2openai 这个

**Comment by zzlKevin** [comment]
这个项目可以结合 https://github.com/duoyang666/ai_novel项目中的 魔改版 OpenWebUi ，OpenWebUi提供前端页面支持
